# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: What Chrome extensions block social-media spying?
email: mail@michael.kropat.name
description: > # this means to ignore newlines until "baseurl:"
  How good are Chrome anti-tracking extensions at protecting you from the
  spying done by the big social media sites (Facebook, Google, Twitter) when
  you're browsing the web? (Specifically, all the time that you're not browsing
  facebook.com, google.com, or twitter.com.)
baseurl: "/social-media-sandbox-audit" # the subpath of your site, e.g. /blog
url: "http://www.codetinkerer.com" # the base hostname & protocol for your site
twitter_username: MichaelKropat
github_username:  mkropat

# Build settings
markdown: kramdown
